apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: posts
          imagePullPolicy: Never
# wszystko w jednym pliku
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: posts-srv
#spec:
#  type: NodePort
#  selector:
#    app: posts
#  ports:
#    - name: posts
#      protocol: TCP
#      port: 4000
#      targetPort: 4000